// Regenerate the committed demo artifact from the seeded generator.
// Fixed seed + fixed base date ⇒ byte-identical output on every run,
// which the test suite asserts (tests/demo.test.mjs).
//
//   node scripts/generate-demo.mjs
import { writeFile, mkdir } from 'node:fs/promises';
import { generateDemoData } from '../js/demo.mjs';
import { mulberry32 } from '../js/engine.mjs';

export const DEMO_SEED = 42;
export const DEMO_BASE_DATE = '2026-07-01T12:00:00.000Z';

export function buildDemoArtifact(){
  const data = generateDemoData({ baseDate: new Date(DEMO_BASE_DATE), rng: mulberry32(DEMO_SEED) });
  return {
    _synthetic: true,
    _note: 'Generated by scripts/generate-demo.mjs — fixed seed, no real data.',
    seed: DEMO_SEED,
    baseDate: DEMO_BASE_DATE,
    ...data
  };
}

if (import.meta.url === `file://${process.argv[1]}`){
  await mkdir('demo/generated', { recursive: true });
  const artifact = buildDemoArtifact();
  await writeFile('demo/generated/demo-data.json', JSON.stringify(artifact, null, 2) + '\n');
  console.log(`demo/generated/demo-data.json written (${artifact.logs.length} synthetic sessions)`);
}
